/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XbalcAmbulanceWlList {
    }
}
declare global {
    interface HTMLXbalcAmbulanceWlListElement extends Components.XbalcAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXbalcAmbulanceWlListElement: {
        prototype: HTMLXbalcAmbulanceWlListElement;
        new (): HTMLXbalcAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xbalc-ambulance-wl-list": HTMLXbalcAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XbalcAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xbalc-ambulance-wl-list": XbalcAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xbalc-ambulance-wl-list": LocalJSX.XbalcAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXbalcAmbulanceWlListElement>;
        }
    }
}
